name: AspireGameshow
version: 0.1-BETA
main: xyz.aspirenetwork.gameshow.Main
api-version: 1.16
authors: [ Torben ]
description: a gameshow plugin for the aspire smp
website: www.theaspiresmp.tk
commands:
  play-background-music:
  history-400:
